# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('players', models.IntegerField()),
                ('gamestate', models.CharField(max_length=1000)),
                ('turn', models.CharField(max_length=1)),
                ('leaver', models.BooleanField(default=False)),
                ('winner', models.CharField(default=b'', max_length=1)),
                ('draw', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
